import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { lstatSync } from "node:fs";
import {
  chmod,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  readlink,
  rename,
  rmdir,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import {
  createG17NativeWorkspace,
  createG17NativeWorkspaceForTesting,
  destroyG17NativeWorkspace,
  g17NativeWorkspaceProjection,
  g17NativeWorkspaceOwnerEvidence,
  materializeG17SourceSnapshotForTesting,
  productionG17RequiredGitlinks,
  verifyG17NativeWorkspace,
} from "../src/qualification/native-workspace.mjs";
import { repositoryRoot } from "../src/paths.mjs";

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function git(root, args, options = {}) {
  return execFileSync("/usr/bin/git", args, {
    cwd: root,
    encoding: options.buffer ? undefined : "utf8",
    env: {
      GIT_CONFIG_GLOBAL: "/dev/null",
      GIT_CONFIG_NOSYSTEM: "1",
      GIT_TERMINAL_PROMPT: "0",
      HOME: "/nonexistent",
      LANG: "C.UTF-8",
      LC_ALL: "C.UTF-8",
      PATH: "/usr/bin:/bin",
      ...options.environment,
    },
    stdio: ["ignore", "pipe", "pipe"],
  });
}

async function createDirtyRepository(root) {
  const repository = join(root, "repository");
  await mkdir(join(repository, "cli"), { recursive: true, mode: 0o700 });
  git(repository, ["init", "--quiet"]);
  await Promise.all([
    writeFile(join(repository, "Cargo.toml"), '[workspace]\nmembers = []\n'),
    writeFile(
      join(repository, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n',
    ),
    writeFile(join(repository, "tracked.txt"), "committed\n"),
    writeFile(join(repository, "cli", "README.md"), "cli\n"),
    symlink("cli", join(repository, "server")),
  ]);
  git(repository, ["add", "--all"]);
  git(repository, ["commit", "--quiet", "-m", "fixture"], {
    environment: {
      GIT_AUTHOR_DATE: "2000-01-01T00:00:00Z",
      GIT_AUTHOR_EMAIL: "fixture@localhost",
      GIT_AUTHOR_NAME: "Fixture",
      GIT_COMMITTER_DATE: "2000-01-01T00:00:00Z",
      GIT_COMMITTER_EMAIL: "fixture@localhost",
      GIT_COMMITTER_NAME: "Fixture",
    },
  });
  const commit = git(repository, ["rev-parse", "HEAD"]).trim();
  const tree = git(repository, ["rev-parse", "HEAD^{tree}"]).trim();
  const cargoLockBlob = git(repository, ["rev-parse", "HEAD:Cargo.lock"]).trim();
  const cargoLockBytes = git(repository, ["show", "HEAD:Cargo.lock"], { buffer: true });
  await Promise.all([
    writeFile(join(repository, "tracked.txt"), "dirty-working-copy\n"),
    writeFile(join(repository, "untracked.txt"), "must-not-enter\n"),
  ]);
  return {
    repository,
    identity: {
      subject: { commit, tree },
      cargoLock: { blob: cargoLockBlob, sha256: sha256(cargoLockBytes) },
    },
  };
}

async function createDependencyFixture(root, { lockVersion = 4 } = {}) {
  const archiveBytes = Buffer.from("deterministic fixture crate archive\n", "utf8");
  const archiveSha256 = sha256(archiveBytes);
  const repository = join(root, "dependency-repository");
  await mkdir(join(repository, "src"), { recursive: true, mode: 0o700 });
  await Promise.all([
    writeFile(
      join(repository, "Cargo.toml"),
      '[package]\nname = "fixture-workspace"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nfixture-dep = "1.2.3"\n',
    ),
    writeFile(
      join(repository, "Cargo.lock"),
      [
        "# This file is automatically @generated by Cargo.",
        `version = ${lockVersion}`,
        "",
        "[[package]]",
        'name = "fixture-dep"',
        'version = "1.2.3"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        `checksum = "${archiveSha256}"`,
        "",
        "[[package]]",
        'name = "fixture-workspace"',
        'version = "0.1.0"',
        "dependencies = [",
        ' "fixture-dep",',
        "]",
        "",
      ].join("\n"),
    ),
    writeFile(join(repository, "src", "lib.rs"), "pub fn fixture() -> bool { true }\n"),
  ]);
  git(repository, ["init", "--quiet"]);
  git(repository, ["add", "--all"]);
  git(repository, ["commit", "--quiet", "-m", "dependency fixture"], {
    environment: {
      GIT_AUTHOR_DATE: "2000-01-01T00:00:00Z",
      GIT_AUTHOR_EMAIL: "fixture@localhost",
      GIT_AUTHOR_NAME: "Fixture",
      GIT_COMMITTER_DATE: "2000-01-01T00:00:00Z",
      GIT_COMMITTER_EMAIL: "fixture@localhost",
      GIT_COMMITTER_NAME: "Fixture",
    },
  });
  const commit = git(repository, ["rev-parse", "HEAD"]).trim();
  const tree = git(repository, ["rev-parse", "HEAD^{tree}"]).trim();
  const cargoLockBlob = git(repository, ["rev-parse", "HEAD:Cargo.lock"]).trim();
  const cargoLockBytes = git(repository, ["show", "HEAD:Cargo.lock"], { buffer: true });
  await writeFile(join(repository, "Cargo.lock"), "dirty live lock must not be used\n");

  const cargoHome = join(root, "host-cargo-home");
  const registryDirectory = "index.crates.io-1949cf8c6b5b557f";
  const sparsePath = join("fi", "xt", "fixture-dep");
  await Promise.all([
    mkdir(join(cargoHome, "registry", "cache", registryDirectory), {
      recursive: true,
      mode: 0o700,
    }),
    mkdir(join(cargoHome, "registry", "index", registryDirectory, ".cache", "fi", "xt"), {
      recursive: true,
      mode: 0o700,
    }),
    mkdir(join(cargoHome, "registry", "src", registryDirectory, "must-not-copy"), {
      recursive: true,
      mode: 0o700,
    }),
    mkdir(join(cargoHome, "registry", "cache", "alternate-registry"), {
      recursive: true,
      mode: 0o700,
    }),
  ]);
  await Promise.all([
    writeFile(
      join(cargoHome, "registry", "cache", registryDirectory, "fixture-dep-1.2.3.crate"),
      archiveBytes,
    ),
    writeFile(
      join(cargoHome, "registry", "index", registryDirectory, "config.json"),
      '{"dl":"https://static.crates.io/crates","api":"https://crates.io"}\n',
    ),
    writeFile(
      join(cargoHome, "registry", "index", registryDirectory, ".cache", sparsePath),
      Buffer.from([3, 2, 1, 0, 102, 105, 120, 116, 117, 114, 101]),
    ),
    writeFile(join(cargoHome, "config.toml"), "must-not-copy = true\n"),
    writeFile(join(cargoHome, "credentials.toml"), "token = 'must-not-copy'\n"),
    writeFile(join(cargoHome, "registry", "src", registryDirectory, "must-not-copy", "secret"), "x"),
    writeFile(join(cargoHome, "registry", "cache", "alternate-registry", "unrelated.crate"), "x"),
  ]);

  const toolchain = join(root, "fake-toolchain", "bin");
  await mkdir(toolchain, { recursive: true, mode: 0o700 });
  const cargoProgram = join(toolchain, "cargo");
  await Promise.all([
    writeFile(cargoProgram, "fixture cargo\n"),
    writeFile(join(toolchain, "rustc"), "fixture rustc\n"),
  ]);
  await Promise.all([chmod(cargoProgram, 0o700), chmod(join(toolchain, "rustc"), 0o700)]);
  return {
    archiveBytes: archiveBytes.length,
    archiveSha256,
    cargoHome,
    cargoProgram,
    identity: {
      subject: { commit, tree },
      cargoLock: { blob: cargoLockBlob, sha256: sha256(cargoLockBytes) },
    },
    repository,
  };
}

test("source snapshot materializes the exact commit and ignores dirty or untracked authority", async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-g17-source-snapshot-"));
  try {
    const { repository, identity } = await createDirtyRepository(root);
    const destinationRoot = join(root, "private");
    await mkdir(destinationRoot, { mode: 0o700 });
    const snapshot = await materializeG17SourceSnapshotForTesting({
      repoRoot: repository,
      identity,
      destinationRoot,
      requiredGitlinks: [],
    });

    assert.equal(snapshot.schema, "oxigraph.g1.7-source-snapshot/v1");
    assert.equal(snapshot.commit, identity.subject.commit);
    assert.equal(snapshot.tree, identity.subject.tree);
    assert.equal(await readFile(join(snapshot.sourceDirectory, "tracked.txt"), "utf8"), "committed\n");
    await assert.rejects(readFile(join(snapshot.sourceDirectory, "untracked.txt")));
    assert.equal(lstatSync(join(snapshot.sourceDirectory, "server")).isSymbolicLink(), true);
    assert.equal(await readlink(join(snapshot.sourceDirectory, "server")), "cli");
    await assert.rejects(readFile(join(snapshot.sourceDirectory, ".git")));
    assert.equal(snapshot.requiredGitlinks.length, 0);
    assert.equal(snapshot.excludedGitlinks.length, 0);
    assert.ok(snapshot.entryCount >= 5);
    assert.match(snapshot.manifestSha256, /^[0-9a-f]{64}$/u);
    assert.equal(snapshot.beforeSha256, snapshot.afterSha256);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production source closure materializes only the pinned RocksDB and LZ4 gitlinks", { timeout: 120_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-g17-production-source-"));
  try {
    const commit = git(repositoryRoot, ["rev-parse", "HEAD"]).trim();
    const tree = git(repositoryRoot, ["rev-parse", "HEAD^{tree}"]).trim();
    const cargoLockBlob = git(repositoryRoot, ["rev-parse", `${commit}:Cargo.lock`]).trim();
    const cargoLockBytes = git(repositoryRoot, ["show", `${commit}:Cargo.lock`], { buffer: true });
    const destinationRoot = join(root, "private");
    await mkdir(destinationRoot, { mode: 0o700 });
    const snapshot = await materializeG17SourceSnapshotForTesting({
      repoRoot: repositoryRoot,
      identity: {
        subject: { commit, tree },
        cargoLock: { blob: cargoLockBlob, sha256: sha256(cargoLockBytes) },
      },
      destinationRoot,
      requiredGitlinks: productionG17RequiredGitlinks(),
    });

    assert.deepEqual(
      snapshot.requiredGitlinks.map(({ path }) => path),
      ["oxrocksdb-sys/lz4", "oxrocksdb-sys/rocksdb"],
    );
    assert.ok(snapshot.excludedGitlinks.some(({ path }) => path === "bench/bsbm-tools"));
    assert.equal(
      await readFile(join(snapshot.sourceDirectory, "oxrocksdb-sys", "lz4", "lib", "lz4.c"), "utf8")
        .then((value) => value.length > 0),
      true,
    );
    assert.equal(
      await readFile(join(snapshot.sourceDirectory, "oxrocksdb-sys", "rocksdb", "src.mk"), "utf8")
        .then((value) => value.length > 0),
      true,
    );
    assert.equal(await readlink(join(snapshot.sourceDirectory, "server")), "cli");
    await assert.rejects(readFile(join(snapshot.sourceDirectory, ".git")));
    await assert.rejects(readFile(join(snapshot.sourceDirectory, "bench", "bsbm-tools", "README")));
    assert.ok(snapshot.entryCount > 1_000);
    assert.match(snapshot.objectClosureSha256, /^[0-9a-f]{64}$/u);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("private workspace derives and verifies an exact offline vendor closure", { timeout: 30_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-g17-private-workspace-"));
  let workspace;
  try {
    const fixture = await createDependencyFixture(root);
    const calls = [];
    const processRunner = async (request) => {
      calls.push(request);
      assert.equal(request.executable, fixture.cargoProgram);
      assert.equal(request.cwd.startsWith(root), true);
      assert.equal(request.environment.CARGO_NET_OFFLINE, "true");
      assert.equal(request.environment.GIT_CONFIG_GLOBAL, "/dev/null");
      if (request.args[0] === "vendor") {
        const vendorDirectory = request.args.at(-1);
        assert.equal(request.args.includes("--respect-source-config"), false);
        assert.equal(request.args.includes("--no-delete"), false);
        assert.equal(request.args.at(-2), join(request.cwd, "Cargo.toml"));
        const packageRoot = join(vendorDirectory, "fixture-dep-1.2.3");
        await mkdir(join(packageRoot, "src"), { recursive: true, mode: 0o700 });
        const cargoToml = Buffer.from(
          '[package]\nname = "fixture-dep"\nversion = "1.2.3"\nedition = "2021"\n',
          "utf8",
        );
        const library = Buffer.from("pub fn dependency() -> bool { true }\n", "utf8");
        await Promise.all([
          writeFile(join(packageRoot, "Cargo.toml"), cargoToml),
          writeFile(join(packageRoot, "src", "lib.rs"), library),
        ]);
        await writeFile(
          join(packageRoot, ".cargo-checksum.json"),
          `${JSON.stringify({
            files: {
              "Cargo.toml": sha256(cargoToml),
              "src/lib.rs": sha256(library),
            },
            package: fixture.archiveSha256,
          })}\n`,
        );
        return Object.freeze({
          disposition: "completed",
          exitCode: 0,
          signal: null,
          durationMs: 7,
          stdout: "vendor complete\n",
          stderr: "",
          terminationErrors: Object.freeze([]),
        });
      }
      assert.equal(request.args[0], "metadata");
      const privateRoot = dirname(dirname(request.environment.CARGO_HOME));
      const sourceDirectory = request.cwd;
      const vendorDirectory = join(privateRoot, "cargo-home", "vendor");
      return Object.freeze({
        disposition: "completed",
        exitCode: 0,
        signal: null,
        durationMs: 5,
        stdout: JSON.stringify({
          packages: [
            {
              name: "fixture-workspace",
              version: "0.1.0",
              source: null,
              manifest_path: join(sourceDirectory, "Cargo.toml"),
            },
            {
              name: "fixture-dep",
              version: "1.2.3",
              source: "registry+https://github.com/rust-lang/crates.io-index",
              manifest_path: join(vendorDirectory, "fixture-dep-1.2.3", "Cargo.toml"),
            },
          ],
          workspace_root: sourceDirectory,
          target_directory: join(privateRoot, "target"),
        }),
        stderr: "",
        terminationErrors: Object.freeze([]),
      });
    };
    const createWorkspace = createG17NativeWorkspaceForTesting({
      sourceCargoHome: fixture.cargoHome,
      temporaryParent: root,
      processRunner,
    });
    workspace = await createWorkspace({
      runId: "fixture",
      repoRoot: fixture.repository,
      identity: fixture.identity,
      cargoProgram: fixture.cargoProgram,
    });

    assert.equal(workspace.schema, "oxigraph.g1.7-native-workspace/v1");
    assert.equal(workspace.dependencies.packageCount, 1);
    assert.equal(workspace.dependencies.archives.count, 1);
    assert.equal(workspace.dependencies.archives.bytes, fixture.archiveBytes);
    assert.equal(workspace.dependencies.archives.records[0].sha256, fixture.archiveSha256);
    assert.equal(workspace.dependencies.sparseBootstrap.uniqueCrateCount, 1);
    assert.equal(workspace.dependencies.sparseBootstrap.records[0].crate, "fixture-dep");
    assert.equal(workspace.dependencies.vendorChecksums.packageCount, 1);
    assert.equal(workspace.dependencies.vendorChecksums.fileCount, 2);
    assert.equal(
      workspace.dependencies.vendorChecksums.packages[0].packageChecksum,
      fixture.archiveSha256,
    );
    assert.deepEqual(
      workspace.dependencies.metadata.packages.map(({ manifestPath }) => manifestPath),
      [
        "/workspace/Cargo.toml",
        "/cargo-home/vendor/fixture-dep-1.2.3/Cargo.toml",
      ],
    );
    assert.equal(workspace.dependencies.vendorCommand.program, "/toolchain/bin/cargo");
    assert.equal(workspace.dependencies.vendorCommand.cwd, "/workspace");
    assert.equal(workspace.dependencies.vendorCommand.argv.at(-2), "/workspace/Cargo.toml");
    assert.equal(workspace.dependencies.vendorCommand.argv.at(-1), "/cargo-home/vendor");
    assert.equal(
      workspace.dependencies.vendorCommand.environment.CARGO_HOME,
      "/control/bootstrap-cargo-home",
    );
    assert.match(workspace.dependencies.vendorCommand.environmentSha256, /^[0-9a-f]{64}$/u);
    assert.equal(JSON.stringify(workspace.dependencies).includes(root), false);
    assert.equal(calls.length, 2);
    assert.equal(calls[0].args[0], "vendor");
    assert.equal(calls[0].args.at(-1), workspace.vendorDirectory);
    assert.equal(calls[1].args[0], "metadata");
    await assert.rejects(readFile(join(workspace.root, "control", "bootstrap-cargo-home")));
    await assert.rejects(readFile(join(workspace.cargoHomeDirectory, "credentials.toml")));
    await assert.rejects(readFile(join(workspace.cargoHomeDirectory, "registry")));
    const finalConfig = await readFile(
      join(workspace.cargoHomeDirectory, "config.toml"),
      "utf8",
    );
    assert.match(finalConfig, /directory = "\/cargo-home\/vendor"/u);
    assert.match(finalConfig, /target-dir = "\/state\/target"/u);
    assert.equal(finalConfig.includes(fixture.cargoHome), false);
    const afterNative = await verifyG17NativeWorkspace(workspace, "after-native");
    assert.equal(afterNative.source.beforeSha256, afterNative.source.afterSha256);
    assert.equal(afterNative.vendor.beforeSha256, afterNative.vendor.afterSha256);
    const projection = g17NativeWorkspaceProjection(workspace);
    assert.equal(projection.dependencies.packageCount, 1);
    assert.equal(Object.hasOwn(projection, "root"), false);
    assert.throws(
      () => g17NativeWorkspaceOwnerEvidence(workspace, afterNative),
      /test workspace cannot mint production owner evidence/u,
    );

    const firstVerification = verifyG17NativeWorkspace(workspace, "verify");
    await assert.rejects(
      verifyG17NativeWorkspace(workspace, "verify"),
      /verification target is not live/u,
    );
    await firstVerification;

    const generatedRoot = workspace.root;
    const displacedRoot = `${generatedRoot}-displaced`;
    await rename(generatedRoot, displacedRoot);
    await mkdir(generatedRoot, { mode: 0o700 });
    await assert.rejects(
      verifyG17NativeWorkspace(workspace, "verify"),
      /root identity or ownership changed/u,
    );
    await assert.rejects(
      destroyG17NativeWorkspace(workspace),
      /cleanup target is not its generated directory/u,
    );
    await rmdir(generatedRoot);
    await rename(displacedRoot, generatedRoot);

    await destroyG17NativeWorkspace(workspace);
    workspace = undefined;
    await assert.rejects(readFile(generatedRoot));
  } finally {
    if (workspace !== undefined) await destroyG17NativeWorkspace(workspace);
    await rm(root, { recursive: true, force: true });
  }
});

test("workspace constructors reject surplus authority before acquisition", () => {
  assert.throws(
    () => createG17NativeWorkspace({
      runId: "fixture",
      repoRoot: "/repository",
      identity: {},
      cargoProgram: "/toolchain/bin/cargo",
      workspaceFactory: () => undefined,
    }),
    /production workspace acquisition input fields are not exact/u,
  );
  assert.throws(
    () => createG17NativeWorkspaceForTesting({
      sourceCargoHome: "/cargo-home",
      temporaryParent: "/tmp",
      processRunner: async () => undefined,
      production: true,
    }),
    /native workspace test factory input fields are not exact/u,
  );
  const createWorkspace = createG17NativeWorkspaceForTesting({
    sourceCargoHome: "/cargo-home",
    temporaryParent: "/tmp",
    processRunner: async () => undefined,
  });
  assert.throws(
    () => createWorkspace({
      runId: "fixture",
      repoRoot: "/repository",
      identity: {},
      cargoProgram: "/toolchain/bin/cargo",
      production: true,
    }),
    /test workspace acquisition input fields are not exact/u,
  );
});

test("private workspace rejects a non-v4 committed lock and removes its generated root", async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-g17-invalid-lock-"));
  try {
    const fixture = await createDependencyFixture(root, { lockVersion: 3 });
    const createWorkspace = createG17NativeWorkspaceForTesting({
      sourceCargoHome: fixture.cargoHome,
      temporaryParent: root,
      processRunner: async () => assert.fail("Cargo must not run for an invalid lock"),
    });
    await assert.rejects(
      createWorkspace({
        runId: "invalid-lock",
        repoRoot: fixture.repository,
        identity: fixture.identity,
        cargoProgram: fixture.cargoProgram,
      }),
      (error) =>
        error?.phase === "cache" &&
        error?.classification === "FAIL" &&
        /lock format version 4/u.test(error.reason),
    );
    assert.equal(
      (await readdir(root)).some((name) => name.startsWith("oxigraph-g17-invalid-lock-")),
      false,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("private workspace rejects a symlinked Cargo cache ancestor", async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-g17-cache-symlink-"));
  try {
    const fixture = await createDependencyFixture(root);
    const registry = join(fixture.cargoHome, "registry");
    await rename(join(registry, "cache"), join(registry, "cache-real"));
    await symlink("cache-real", join(registry, "cache"));
    const createWorkspace = createG17NativeWorkspaceForTesting({
      sourceCargoHome: fixture.cargoHome,
      temporaryParent: root,
      processRunner: async () => assert.fail("Cargo must not run through a symlinked cache"),
    });
    await assert.rejects(
      createWorkspace({
        runId: "cache-symlink",
        repoRoot: fixture.repository,
        identity: fixture.identity,
        cargoProgram: fixture.cargoProgram,
      }),
      (error) =>
        error?.phase === "cache" &&
        error?.classification === "FAIL" &&
        /symlink component/u.test(error.reason),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
