import assert from "node:assert/strict";
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import test from "node:test";
import { setTimeout as delay } from "node:timers/promises";
import { runSandboxCommand } from "../src/candidate/sandbox.mjs";

async function waitForFile(path, timeoutMs = 7_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await access(path);
      return;
    } catch {
      await delay(25);
    }
  }
  throw new Error(`timed out waiting for sandbox marker: ${path}`);
}

test("cancelling an adversarial Cargo build reaps it without escaping the verifier sandbox", async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-sandbox-cancel-"));
  const workspace = join(root, "workspace");
  const targetRoot = join(root, "target");
  const commandTemp = join(root, "tmp");
  const outsideEscape = join(root, "outside-escape");
  const workspaceEscape = join(workspace, "workspace-escape");
  const report = join(commandTemp, "security-report");
  const started = join(commandTemp, "started");
  const heartbeat = join(commandTemp, "heartbeat");
  const mirroredEscape = join(commandTemp, basename(root), "outside-escape");
  const controller = new AbortController();
  let running;

  try {
    await Promise.all(
      [workspace, targetRoot, commandTemp, join(workspace, "src")].map((path) =>
        mkdir(path, { mode: 0o700, recursive: true }),
      ),
    );
    await Promise.all([
      writeFile(
        join(workspace, "Cargo.toml"),
        '[package]\nname = "sandbox-adversary"\nversion = "0.1.0"\nedition = "2021"\nbuild = "build.rs"\n',
        { mode: 0o600 },
      ),
      writeFile(
        join(workspace, "Cargo.lock"),
        '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "sandbox-adversary"\nversion = "0.1.0"\n',
        { mode: 0o600 },
      ),
      writeFile(
        join(workspace, "src", "lib.rs"),
        "pub fn answer() -> u8 { 42 }\n",
        { mode: 0o600 },
      ),
      writeFile(
        join(workspace, "build.rs"),
        `use std::{fs, net::{SocketAddr, TcpStream}, path::Path, thread, time::Duration};

fn attempt_write(path: &str) -> &'static str {
    match fs::write(path, b"escaped") {
        Ok(()) => "unexpected",
        Err(_) => "blocked",
    }
}

extern "C" {
    fn signal(signal: i32, handler: usize) -> usize;
}

fn main() {
    // Make cancellation exercise the sandbox tree boundary instead of relying
    // on a cooperative build script.
    unsafe { signal(15, 1); }
    let workspace = attempt_write("/workspace/workspace-escape");
    let alleged_host_path = ${JSON.stringify(outsideEscape)};
    let _ = fs::create_dir_all(Path::new(alleged_host_path).parent().unwrap());
    let redirected = attempt_write(alleged_host_path);
    let address: SocketAddr = "1.1.1.1:53".parse().unwrap();
    let network = match TcpStream::connect_timeout(&address, Duration::from_millis(250)) {
        Ok(_) => "unexpected",
        Err(_) => "blocked",
    };
    fs::write(
        "/tmp/security-report",
        format!("workspace={workspace}\\nredirected={redirected}\\nnetwork={network}\\n"),
    ).unwrap();
    fs::write("/tmp/started", b"ready").unwrap();
    let mut counter: u64 = 0;
    loop {
        counter += 1;
        fs::write("/tmp/heartbeat", counter.to_string()).unwrap();
        thread::sleep(Duration::from_millis(20));
    }
}
`,
        { mode: 0o600 },
      ),
    ]);

    const runStartedAt = Date.now();
    running = runSandboxCommand({
      workspace,
      targetRoot,
      commandTemp,
      argv: ["cargo", "test", "--no-run", "--offline", "--jobs", "1"],
      timeoutMs: 15_000,
      maxOutputBytes: 64 * 1024,
      cargoBuildJobs: 1,
      signal: controller.signal,
    });

    await waitForFile(started);
    await waitForFile(heartbeat);
    const probeReport = await readFile(report, "utf8");
    assert.equal(
      probeReport,
      "workspace=blocked\nredirected=unexpected\nnetwork=blocked\n",
    );
    controller.abort();

    const result = await running;
    assert.equal(result.outcome.disposition, "cancelled");
    assert.notEqual(result.outcome.exitCode, 0);
    assert.deepEqual(result.outcome.terminationErrors, []);
    assert.ok(
      Date.now() - runStartedAt < 10_000,
      "cancelled build exceeded ten seconds",
    );

    await assert.rejects(access(workspaceEscape));
    await assert.rejects(access(outsideEscape));
    assert.equal(await readFile(mirroredEscape, "utf8"), "escaped");
    assert.ok(
      (await readdir(targetRoot)).length > 0,
      "Cargo did not use the writable target mount",
    );

    const heartbeatAfterReap = await readFile(heartbeat, "utf8");
    const heartbeatMetadataAfterReap = await stat(heartbeat);
    await delay(400);
    assert.equal(await readFile(heartbeat, "utf8"), heartbeatAfterReap);
    assert.equal(
      (await stat(heartbeat)).mtimeMs,
      heartbeatMetadataAfterReap.mtimeMs,
    );
  } finally {
    controller.abort();
    await running?.catch(() => {});
    await rm(root, { recursive: true, force: true });
  }
});
