import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import {
  access,
  mkdir,
  mkdtemp,
  open,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import test from "node:test";
import { runBoundedProcess } from "../src/native/process.mjs";
import {
  runSandboxVerificationSession,
  sandboxSessionArguments,
} from "../src/candidate/sandbox-session.mjs";

const mebibyte = 1024 * 1024;

function commandPlan() {
  return Object.freeze({
    format: Object.freeze({
      argv: Object.freeze(["cargo", "fmt", "--all", "--", "--check"]),
      timeoutMs: 30_000,
    }),
    build: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--no-run",
        "--test",
        "public",
        "--test",
        "independent",
        "--test",
        "regression",
      ]),
      timeoutMs: 90_000,
    }),
    public: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "public"]),
      timeoutMs: 30_000,
    }),
    independent: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "independent"]),
      timeoutMs: 30_000,
    }),
    regression: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "regression"]),
      timeoutMs: 30_000,
    }),
  });
}

async function createFixture(root) {
  const workspace = join(root, "workspace");
  await Promise.all([
    mkdir(join(workspace, "src"), { recursive: true, mode: 0o700 }),
    mkdir(join(workspace, "tests"), { recursive: true, mode: 0o700 }),
  ]);
  await Promise.all([
    writeFile(
      join(workspace, "Cargo.toml"),
      '[package]\nname = "session_fixture"\nversion = "0.1.0"\nedition = "2021"\n',
    ),
    writeFile(
      join(workspace, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "session_fixture"\nversion = "0.1.0"\n',
    ),
    writeFile(
      join(workspace, "src", "lib.rs"),
      "pub fn answer() -> u8 {\n    42\n}\n",
    ),
    writeFile(
      join(workspace, "src", "main.rs"),
      "fn main() {\n    assert_eq!(session_fixture::answer(), 42);\n}\n",
    ),
    ...["public", "independent", "regression"].map((name) =>
      writeFile(
        join(workspace, "tests", `${name}.rs`),
        [
          "#[test]",
          "fn evaluator_is_green() {",
          "    assert_eq!(",
          '        std::env::var("CARGO_INCREMENTAL").expect("incremental control"),',
          '        "0"',
          "    );",
          "    assert_eq!(",
          '        std::env::var("CARGO_PROFILE_TEST_DEBUG").expect("debug control"),',
          '        "0"',
          "    );",
          "    assert_eq!(session_fixture::answer(), 42);",
          "}",
          "",
        ].join("\n"),
      ),
    ),
  ]);
  return workspace;
}

function binaryCommandPlan() {
  return Object.freeze({
    ...commandPlan(),
    build: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--no-run",
        "--test",
        "independent",
        "--bin",
        "session_fixture",
      ]),
      timeoutMs: 90_000,
    }),
    public: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--bin",
        "session_fixture",
      ]),
      timeoutMs: 30_000,
    }),
  });
}

function serviceCommandPlan() {
  const plan = commandPlan();
  return Object.freeze({
    format: plan.format,
    build: plan.build,
    public: plan.public,
    service: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--test",
        "public",
        "evaluator_is_green",
      ]),
      timeoutMs: 30_000,
    }),
    independent: plan.independent,
    regression: plan.regression,
  });
}

async function createAnchorProbeFixture(root) {
  const workspace = await createFixture(root);
  await writeFile(
    join(workspace, "Cargo.toml"),
    '[package]\nname = "session_fixture"\nversion = "0.1.0"\nedition = "2021"\nbuild = "build.rs"\n',
  );
  await writeFile(
    join(workspace, "build.rs"),
    [
      "use std::ffi::{c_char, c_void, CString};",
      "use std::fs;",
      "",
      'unsafe extern "C" {',
      "    fn mount(",
      "        source: *const c_char,",
      "        target: *const c_char,",
      "        filesystem_type: *const c_char,",
      "        mount_flags: usize,",
      "        data: *const c_void,",
      "    ) -> i32;",
      "    fn unshare(flags: i32) -> i32;",
      "}",
      "",
      "fn main() {",
      '    for (source, destination) in [',
      '        ("/state/home", "/state/home-moved"),',
      '        ("/state/tmp", "/state/tmp-moved"),',
      '        ("/state/target", "/state/target-moved"),',
      '    ] {',
      '        assert!(',
      '            fs::rename(source, destination).is_err(),',
      '            "a verifier state anchor was renameable"',
      '        );',
      '    }',
      '    let probe = std::env::temp_dir().join("oxigraph-anchor-probe");',
      '    fs::write(&probe, b"bounded").expect("the protected temp anchor must stay writable");',
      '    fs::remove_file(probe).expect("the temp probe must be removable");',
      "    const CLONE_NEWUSER: i32 = 0x1000_0000;",
      "    const CLONE_NEWNS: i32 = 0x0002_0000;",
      "    // SAFETY: the fixed namespace flags have no pointer arguments.",
      "    assert_ne!(unsafe { unshare(CLONE_NEWUSER | CLONE_NEWNS) }, 0);",
      '    let source = CString::new("none").expect("the source has no NUL");',
      '    let target = CString::new("/state/tmp").expect("the target has no NUL");',
      '    let file_system = CString::new("tmpfs").expect("the file system has no NUL");',
      "    // SAFETY: every string is NUL-terminated and data is unused for this probe.",
      "    assert_ne!(",
      "        unsafe {",
      "            mount(",
      "                source.as_ptr(),",
      "                target.as_ptr(),",
      "                file_system.as_ptr(),",
      "                0,",
      "                std::ptr::null(),",
      "            )",
      "        },",
      "        0,",
      "    );",
      '    assert!(fs::write("/dev/oxigraph-quota-escape", b"escape").is_err());',
      "}",
      "",
    ].join("\n"),
  );
  return workspace;
}

async function createAnchorMutationFixture(root) {
  const workspace = await createFixture(root);
  await writeFile(
    join(workspace, "Cargo.toml"),
    '[package]\nname = "session_fixture"\nversion = "0.1.0"\nedition = "2021"\nbuild = "build.rs"\n',
  );
  await writeFile(
    join(workspace, "build.rs"),
    [
      "use std::fs;",
      "use std::os::unix::fs::PermissionsExt;",
      "",
      "fn main() {",
      '    fs::set_permissions("/state/tmp", fs::Permissions::from_mode(0o700))',
      '        .expect("the mutation probe must reach the writable anchor");',
      "}",
      "",
    ].join("\n"),
  );
  return workspace;
}

async function processRecordsMatching(needles) {
  const records = [];
  for (const entry of await readdir("/proc", { withFileTypes: true })) {
    if (!entry.isDirectory() || !/^\d+$/.test(entry.name)) continue;
    try {
      const commandLine = (await readFile(`/proc/${entry.name}/cmdline`))
        .toString("utf8")
        .replaceAll("\0", " ");
      if (!needles.some((needle) => commandLine.includes(needle))) continue;
      const stat = (await readFile(`/proc/${entry.name}/stat`, "utf8")).trim();
      const close = stat.lastIndexOf(")");
      const fields = stat.slice(close + 2).split(" ");
      records.push(
        Object.freeze({
          pid: Number(entry.name),
          startTime: fields[19],
          commandLine,
        }),
      );
    } catch (error) {
      if (!["ENOENT", "ESRCH"].includes(error.code)) throw error;
    }
  }
  return records;
}

async function waitForProcesses(needles, deadlineMs, earlyFailure = () => null) {
  const deadline = Date.now() + deadlineMs;
  for (;;) {
    const failure = earlyFailure();
    if (failure !== null) throw failure;
    const records = await processRecordsMatching(needles);
    if (records.length > 0) return records;
    if (Date.now() >= deadline) {
      throw new Error(`timed out waiting for process evidence: ${needles.join(", ")}`);
    }
    await delay(25);
  }
}

async function waitForNoProcesses(needles, deadlineMs) {
  const deadline = Date.now() + deadlineMs;
  for (;;) {
    const records = await processRecordsMatching(needles);
    if (records.length === 0) return;
    if (Date.now() >= deadline) {
      throw new Error(`verifier process tree survived cancellation: ${records.map(({ commandLine }) => commandLine).join(" | ")}`);
    }
    await delay(25);
  }
}

async function originalProcessIsGone(record) {
  try {
    const stat = (await readFile(`/proc/${record.pid}/stat`, "utf8")).trim();
    const close = stat.lastIndexOf(")");
    const fields = stat.slice(close + 2).split(" ");
    return fields[19] !== record.startTime;
  } catch (error) {
    if (["ENOENT", "ESRCH"].includes(error.code)) return true;
    throw error;
  }
}

async function createSlowFixture(root, token) {
  const workspace = join(root, "slow-workspace");
  await Promise.all([
    mkdir(join(workspace, "src"), { recursive: true, mode: 0o700 }),
    mkdir(join(workspace, "tests"), { recursive: true, mode: 0o700 }),
  ]);
  const buildScript = [
    "use std::process::Command;",
    "use std::thread;",
    "use std::time::Duration;",
    "",
    "fn main() {",
    '    let mut escaped = Command::new("/usr/bin/setsid")',
    '        .arg("/usr/bin/node")',
    '        .arg("-e")',
    '        .arg("setInterval(() => {}, 1000)")',
    `        .arg("${token}")`,
    '        .spawn()',
    '        .expect("spawn escaped cancellation sentinel");',
    '    println!("cargo:warning=slow verifier sentinel started");',
    "    thread::sleep(Duration::from_secs(60));",
    "    let _ = escaped.kill();",
    "}",
    "",
  ].join("\n");
  await Promise.all([
    writeFile(
      join(workspace, "Cargo.toml"),
      '[package]\nname = "slow_session_fixture"\nversion = "0.1.0"\nedition = "2021"\nbuild = "build.rs"\n',
    ),
    writeFile(
      join(workspace, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "slow_session_fixture"\nversion = "0.1.0"\n',
    ),
    writeFile(join(workspace, "build.rs"), buildScript),
    writeFile(join(workspace, "src", "lib.rs"), "pub fn ready() -> bool {\n    true\n}\n"),
    ...["slow", "independent", "regression"].map((name) =>
      writeFile(
        join(workspace, "tests", `${name}.rs`),
        '#[test]\nfn evaluator_is_green() {\n    assert!(slow_session_fixture::ready());\n}\n',
      ),
    ),
  ]);
  return workspace;
}

function slowCommandPlan() {
  return Object.freeze({
    format: Object.freeze({
      argv: Object.freeze(["cargo", "fmt", "--all", "--", "--check"]),
      timeoutMs: 5_000,
    }),
    build: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--no-run",
        "--test",
        "slow",
        "--test",
        "independent",
        "--test",
        "regression",
      ]),
      timeoutMs: 12_000,
    }),
    public: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "slow"]),
      timeoutMs: 5_000,
    }),
    independent: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "independent"]),
      timeoutMs: 5_000,
    }),
    regression: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "regression"]),
      timeoutMs: 5_000,
    }),
  });
}

test("one quota-bound namespace preserves build state across every evaluator", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-test-"));
  try {
    const workspace = await createFixture(root);
    const output = join(root, "structural-result.json");
    const descriptor = await open(output, "wx", 0o600);
    await descriptor.close();
    const maxDiskBytes = 512 * mebibyte;
    const structural = sandboxSessionArguments({
      workspace,
      outputFile: output,
      maxDiskBytes,
      cargoBuildJobs: 2,
    });
    const stateMount = structural.indexOf("--tmpfs");
    assert.equal(structural[stateMount - 2], "--size");
    assert.equal(structural[stateMount - 1], String(maxDiskBytes));
    assert.equal(structural[stateMount + 1], "/state");
    assert.ok(structural.includes("--unshare-net"));
    assert.ok(structural.includes("--unshare-pid"));
    assert.ok(structural.includes("--clearenv"));
    const incrementalIndex = structural.indexOf("CARGO_INCREMENTAL");
    assert.ok(incrementalIndex > 0);
    assert.equal(structural[incrementalIndex - 1], "--setenv");
    assert.equal(structural[incrementalIndex + 1], "0");
    const testDebugIndex = structural.indexOf("CARGO_PROFILE_TEST_DEBUG");
    assert.ok(testDebugIndex > 0);
    assert.equal(structural[testDebugIndex - 1], "--setenv");
    assert.equal(structural[testDebugIndex + 1], "0");
    assert.ok(structural.includes("--remount-ro"));
    assert.notEqual(
      structural.findIndex(
        (value, index) =>
          value === "--dev" &&
          structural[index + 1] === "/dev" &&
          structural[index + 2] === "--remount-ro" &&
          structural[index + 3] === "/dev",
      ),
      -1,
    );
    const workspaceIndex = structural.indexOf("/workspace");
    assert.equal(structural[workspaceIndex - 2], "--ro-bind");
    assert.ok(!structural.includes("/target"));

    const report = await runSandboxVerificationSession({
      workspace,
      commands: commandPlan(),
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "completed", report.session.error);
    assert.equal(
      report.session.stage,
      "complete",
      report.session.commands.map(({ stderr, stdout }) => `${stdout}\n${stderr}`).join("\n"),
    );
    assert.deepEqual(
      report.session.commands.map(({ name }) => name),
      ["format", "build", "public", "independent", "regression"],
    );
    assert.ok(
      report.session.commands.every(
        ({ disposition, exitCode }) => disposition === "completed" && exitCode === 0,
      ),
    );
    assert.ok(
      report.session.commands.every(
        ({ diagnostic }) =>
          diagnostic.primaryClass === null &&
          diagnostic.rustcCodes.length === 0 &&
          diagnostic.childTermination === null &&
          diagnostic.ioErrno === null,
      ),
    );
    assert.deepEqual(
      new Set(report.session.artifacts.map(({ name }) => name.split("-")[0])),
      new Set(["public", "independent", "regression"]),
    );
    assert.ok(report.session.artifacts.every(({ sha256 }) => /^[a-f0-9]{64}$/.test(sha256)));
    assert.ok(report.session.stateBytes > 0 && report.session.stateBytes <= maxDiskBytes);
    assert.equal(report.invocation.network, "isolated");
    assert.equal(report.invocation.workspace, "read-only");
    assert.equal(report.invocation.state, "single-quota-tmpfs");
    await assert.rejects(access(join(workspace, "target")));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production verifier protects writable state anchors from candidate code", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-anchor-test-"));
  try {
    const workspace = await createAnchorProbeFixture(root);
    const report = await runSandboxVerificationSession({
      workspace,
      commands: commandPlan(),
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes: 512 * mebibyte,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "completed", report.session.error);
    assert.equal(
      report.session.stage,
      "complete",
      report.session.commands.map(({ stderr, stdout }) => `${stdout}\n${stderr}`).join("\n"),
    );
    assert.ok(
      report.session.commands.every(
        ({ disposition, exitCode }) => disposition === "completed" && exitCode === 0,
      ),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production verifier executes the optional service evaluator as its own bounded stage", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-service-test-"));
  try {
    const workspace = await createFixture(root);
    const report = await runSandboxVerificationSession({
      workspace,
      commands: serviceCommandPlan(),
      verificationSequence: [
        "format",
        "build",
        "public",
        "service",
        "independent",
        "regression",
      ],
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes: 512 * mebibyte,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "completed", report.session.error);
    assert.equal(report.session.stage, "complete");
    assert.deepEqual(
      report.session.commands.map(({ name }) => name),
      ["format", "build", "public", "service", "independent", "regression"],
    );
    assert.match(
      report.session.commands.find(({ name }) => name === "service").stdout,
      /test result: ok\. 1 passed; 0 failed;/u,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production verifier attests exact mixed binary and test build targets", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-bin-test-"));
  try {
    const workspace = await createFixture(root);
    const report = await runSandboxVerificationSession({
      workspace,
      commands: binaryCommandPlan(),
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes: 512 * mebibyte,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "completed", report.session.error);
    assert.equal(report.session.stage, "complete");
    assert.deepEqual(
      new Set(report.session.artifacts.map(({ name }) => name.split("-")[0])),
      new Set(["independent", "session_fixture"]),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production verifier treats state-anchor mutation as infrastructure failure", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-anchor-mutation-test-"));
  try {
    const workspace = await createAnchorMutationFixture(root);
    const report = await runSandboxVerificationSession({
      workspace,
      commands: commandPlan(),
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes: 512 * mebibyte,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "error");
    assert.equal(report.session.stage, "infrastructure");
    assert.deepEqual(report.session.commands, []);
    assert.deepEqual(report.session.artifacts, []);
    assert.match(report.session.error, /StateInvariantError: verifier state anchor identity changed: temp/u);
    assert.doesNotMatch(report.session.error, /\/state|target|debug|deps/u);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("production aggregate verifier cancellation reaps an escaped Cargo tree and cleans private state", { timeout: 20_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-cancel-test-"));
  const token = `oxigraph-cancel-${process.pid}-${randomUUID()}`;
  let privateOutputRoot;
  let earlyFailure = null;
  try {
    const workspace = await createSlowFixture(root, token);
    const controller = new AbortController();
    const running = runSandboxVerificationSession({
      workspace,
      commands: slowCommandPlan(),
      maxTotalWallMs: 15_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes: 256 * mebibyte,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
      signal: controller.signal,
      processRunner: async (request) => {
        const resultDestination = request.args.indexOf("/result/session.json");
        assert.ok(resultDestination > 0, "production bwrap invocation must bind one result file");
        privateOutputRoot = dirname(request.args[resultDestination - 1]);
        return runBoundedProcess(request);
      },
    });
    running.catch((error) => {
      earlyFailure = error;
    });

    const live = await waitForProcesses(
      [token],
      8_000,
      () => earlyFailure,
    );
    assert.ok(privateOutputRoot?.startsWith(join(tmpdir(), "oxigraph-verifier-session-")));
    const namespaceProcesses = await processRecordsMatching([privateOutputRoot]);
    assert.ok(namespaceProcesses.length > 0, "systemd/bwrap invocation was not observable");
    controller.abort();

    let cancellation;
    try {
      await running;
      assert.fail("cancelled verifier unexpectedly completed");
    } catch (error) {
      cancellation = error;
    }
    assert.equal(cancellation.outcome.disposition, "cancelled");
    assert.equal(cancellation.outcome.terminationErrors.length, 0);

    await waitForNoProcesses([token, privateOutputRoot], 5_000);
    for (const record of [...live, ...namespaceProcesses]) {
      assert.equal(await originalProcessIsGone(record), true, `PID ${record.pid} was not reaped`);
    }
    await assert.rejects(access(privateOutputRoot));
    await assert.rejects(access(join(workspace, "target")));
    await assert.rejects(access(join(root, "state")));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
