import assert from "node:assert/strict";
import {
  access,
  mkdir,
  mkdtemp,
  open,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  runSandboxVerificationSession,
  sandboxSessionArguments,
} from "../src/candidate/sandbox-session.mjs";

const mebibyte = 1024 * 1024;

function commandPlan() {
  return Object.freeze({
    format: Object.freeze({
      argv: Object.freeze(["cargo", "fmt", "--all", "--", "--check"]),
      timeoutMs: 30_000,
    }),
    build: Object.freeze({
      argv: Object.freeze([
        "cargo",
        "test",
        "--locked",
        "--no-run",
        "--test",
        "public",
        "--test",
        "independent",
        "--test",
        "regression",
      ]),
      timeoutMs: 90_000,
    }),
    public: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "public"]),
      timeoutMs: 30_000,
    }),
    independent: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "independent"]),
      timeoutMs: 30_000,
    }),
    regression: Object.freeze({
      argv: Object.freeze(["cargo", "test", "--locked", "--test", "regression"]),
      timeoutMs: 30_000,
    }),
  });
}

async function createFixture(root) {
  const workspace = join(root, "workspace");
  await Promise.all([
    mkdir(join(workspace, "src"), { recursive: true, mode: 0o700 }),
    mkdir(join(workspace, "tests"), { recursive: true, mode: 0o700 }),
  ]);
  await Promise.all([
    writeFile(
      join(workspace, "Cargo.toml"),
      '[package]\nname = "session_fixture"\nversion = "0.1.0"\nedition = "2021"\n',
    ),
    writeFile(
      join(workspace, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "session_fixture"\nversion = "0.1.0"\n',
    ),
    writeFile(
      join(workspace, "src", "lib.rs"),
      "pub fn answer() -> u8 {\n    42\n}\n",
    ),
    ...["public", "independent", "regression"].map((name) =>
      writeFile(
        join(workspace, "tests", `${name}.rs`),
        '#[test]\nfn evaluator_is_green() {\n    assert_eq!(session_fixture::answer(), 42);\n}\n',
      ),
    ),
  ]);
  return workspace;
}

test("one quota-bound namespace preserves build state across every evaluator", { timeout: 180_000 }, async () => {
  const root = await mkdtemp(join(tmpdir(), "oxigraph-session-test-"));
  try {
    const workspace = await createFixture(root);
    const output = join(root, "structural-result.json");
    const descriptor = await open(output, "wx", 0o600);
    await descriptor.close();
    const maxDiskBytes = 512 * mebibyte;
    const structural = sandboxSessionArguments({
      workspace,
      outputFile: output,
      maxDiskBytes,
      cargoBuildJobs: 2,
    });
    const stateMount = structural.indexOf("--tmpfs");
    assert.equal(structural[stateMount - 2], "--size");
    assert.equal(structural[stateMount - 1], String(maxDiskBytes));
    assert.equal(structural[stateMount + 1], "/state");
    assert.ok(structural.includes("--unshare-net"));
    assert.ok(structural.includes("--unshare-pid"));
    assert.ok(structural.includes("--clearenv"));
    assert.ok(structural.includes("--remount-ro"));
    const workspaceIndex = structural.indexOf("/workspace");
    assert.equal(structural[workspaceIndex - 2], "--ro-bind");
    assert.ok(!structural.includes("/target"));

    const report = await runSandboxVerificationSession({
      workspace,
      commands: commandPlan(),
      maxTotalWallMs: 150_000,
      maxResidentBytes: 2 * 1024 * mebibyte,
      maxDiskBytes,
      cargoBuildJobs: 2,
      maxBuildOutputBytes: mebibyte,
      maxTestOutputBytesPerCommand: mebibyte,
    });
    assert.equal(report.session.status, "completed", report.session.error);
    assert.equal(
      report.session.stage,
      "complete",
      report.session.commands.map(({ stderr, stdout }) => `${stdout}\n${stderr}`).join("\n"),
    );
    assert.deepEqual(
      report.session.commands.map(({ name }) => name),
      ["format", "build", "public", "independent", "regression"],
    );
    assert.ok(
      report.session.commands.every(
        ({ disposition, exitCode }) => disposition === "completed" && exitCode === 0,
      ),
    );
    assert.deepEqual(
      new Set(report.session.artifacts.map(({ name }) => name.split("-")[0])),
      new Set(["public", "independent", "regression"]),
    );
    assert.ok(report.session.artifacts.every(({ sha256 }) => /^[a-f0-9]{64}$/.test(sha256)));
    assert.ok(report.session.stateBytes > 0 && report.session.stateBytes <= maxDiskBytes);
    assert.equal(report.invocation.network, "isolated");
    assert.equal(report.invocation.workspace, "read-only");
    assert.equal(report.invocation.state, "single-quota-tmpfs");
    await assert.rejects(access(join(workspace, "target")));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
