export const reviewedObligations = [
  obligation(
    "core-entailment-unsupported-failure",
    "core",
    "shacl-rdfs",
    "MUST",
    "An unsupported sh:entailment regime signals failure; non-IRI values are ill-formed.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/conformance.rs", "compile::tests::fails_closed_for_requested_entailment_regimes"],
  ),
  obligation(
    "core-validation-input-immutability",
    "core",
    "validation-definition",
    "MUST",
    "Validation does not mutate the data graph or shapes graph.",
    "implemented-by-api",
    ["lib/oxshacl/src/model.rs", "lib/oxshacl/src/validate.rs"],
  ),
  obligation(
    "core-well-formed-shapes-graph",
    "core",
    "shapes-graph-well-formed",
    "MUST",
    "Complete Core conformance requires all syntax rules and compatible import closure.",
    "residual-not-claimed",
    ["lib/oxshacl/src/profile.rs", "compile::tests::complete_claim_remains_unavailable"],
  ),
  obligation(
    "core-report-graph",
    "core",
    "validation-report",
    "MUST",
    "Validation report graph contents are compared exactly after canonicalization.",
    "implemented-tested",
    ["lib/oxshacl/examples/w3c_runner/report_compare.rs", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "core-subclass-hierarchy-source",
    "core",
    "subClassOfInShapesGraph",
    "SHOULD",
    "Applications can include shapes-graph rdfs:subClassOf triples in SHACL type checks.",
    "implemented-tested",
    ["lib/oxshacl/src/control.rs", "validate::semantics::tests::subclass_hierarchy_can_include_the_shapes_graph"],
  ),
  obligation(
    "core-shapes-graph-well-formed-flag",
    "core",
    "validation-report",
    "SHOULD",
    "A processor checking complete well-formedness should report sh:shapesGraphWellFormed.",
    "implemented-tested-opt-in",
    [
      "lib/oxshacl/src/report.rs",
      "core_well_formed::well_formed_report_term_is_opt_in_and_requires_certifying_compile",
    ],
  ),
  obligation(
    "sparql-prefix-collection",
    "sparql",
    "sparql-prefixes",
    "MUST",
    "Explicit prefix roots, inverse owl:versionIRI/import closure, datatypes, and duplicate mappings are enforced.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/prefixes.rs"],
  ),
  obligation(
    "sparql-resulting-query-parse",
    "sparql",
    "sparql-prefixes",
    "MUST",
    "The resulting query is parsed during compilation and parse errors signal failure.",
    "implemented-tested",
    ["lib/oxshacl/src/sparql/policy.rs"],
  ),
  obligation(
    "sparql-prebinding-restrictions",
    "sparql",
    "pre-binding",
    "MUST",
    "MINUS, pre-bound VALUES variables, and AS rebinding are rejected structurally; SERVICE is disabled fail-closed.",
    "implemented-tested",
    ["sparql::policy::tests::rejects_values_and_as_for_any_prebound_variable"],
  ),
  obligation(
    "sparql-path-substitution",
    "sparql",
    "PATH-position",
    "MUST",
    "PATH occurs only as a triple predicate and is replaced by valid surface syntax for complex SHACL paths.",
    "implemented-tested",
    ["lib/oxshacl/src/path.rs", "sparql::policy::tests::substitutes_only_legal_path_variables"],
  ),
  obligation(
    "sparql-solution-failure",
    "sparql",
    "sparql-constraints-validation-rule",
    "MUST",
    "A true ?failure solution aborts validation and does not create a result.",
    "implemented-tested",
    ["sparql::tests::true_failure_binding_aborts_validation"],
  ),
  obligation(
    "sparql-result-mapping",
    "sparql",
    "sparql-constraints-variables",
    "MUST",
    "Focus, value, path, message, severity, source constraint, and component bindings map to results.",
    "implemented-tested",
    [
      "sparql::tests::explicit_result_bindings_map_in_normative_precedence_order",
      "sparql::tests::completed_results_apply_property_shape_and_custom_component_fallbacks",
      "sparql::tests::an_unbound_value_maps_only_when_the_value_node_is_unambiguous",
    ],
  ),
  obligation(
    "sparql-message-interpolation",
    "sparql",
    "sparql-constraints-variables",
    "SHOULD",
    "Declared messages interpolate SELECT bindings and custom parameter bindings.",
    "implemented-tested",
    ["sparql::tests::solution_bindings_interpolate_declared_messages"],
  ),
  obligation(
    "sparql-result-annotations",
    "sparql",
    "sparql-constraints-annotations",
    "MAY",
    "Declared result annotations use solution bindings or constant fallbacks and are emitted on validation-result nodes.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/result_annotations.rs", "lib/oxshacl/tests/result_annotations.rs"],
  ),
  obligation(
    "sparql-custom-parameter-syntax",
    "sparql",
    "constraint-components-parameters",
    "MUST",
    "Parameter NCNames, VARNAMEs, reserved names, uniqueness, boolean optionality, and a mandatory parameter are enforced.",
    "implemented-tested",
    [
      "compile::custom::tests::extracts_the_longest_eligible_ncname_suffix",
      "compile::custom::tests::constraint_components_and_parameter_paths_have_required_node_kinds_and_counts",
      "compile::custom::tests::parameter_names_must_be_varnames_unique_and_not_reserved",
      "compile::custom::tests::optional_parameters_require_one_valid_boolean_and_one_mandatory_peer",
    ],
  ),
  obligation(
    "sparql-parameter-shape-conformance",
    "sparql",
    "constraint-components-parameters",
    "MUST",
    "Constraint values conform to constraints declared on parameter shapes.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/custom.rs", "compile::tests::custom_parameter_shapes_are_enforced"],
  ),
  obligation(
    "sparql-validator-query-roles",
    "sparql",
    "constraint-components-validators",
    "MUST",
    "Every declared validator is checked: node/property validators are SELECT and generic validators are ASK.",
    "implemented-tested",
    [
      "lib/oxshacl/src/compile/custom.rs",
      "compile::custom::tests::validator_properties_enforce_their_normative_query_roles",
      "compile::custom::tests::every_declared_validator_is_syntax_checked_even_when_not_selected",
    ],
  ),
  obligation(
    "sparql-select-expression-syntax",
    "sparql",
    "SelectExpression",
    "MUST",
    "SELECT expressions use one xsd:string query, project exactly one in-scope variable, and have at most one prefix root.",
    "implemented-tested",
    [
      "lib/oxshacl/src/compile/node_expression.rs",
      "node_expressions::sparql_select_expression_syntax_is_checked_before_evaluation",
    ],
  ),
  obligation(
    "node-expression-processor",
    "nodeExpressions",
    "conformance",
    "MUST",
    "Pinned node-expression syntax and evaluation fixtures pass exactly.",
    "implemented-tested",
    ["target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "node-by-expression-source-copy",
    "nodeExpressions",
    "nodeByExpression",
    "MUST",
    "Blank output shapes used as sourceConstraint are deep-copied into the report.",
    "implemented-tested",
    ["lib/oxshacl/src/report.rs", "report::tests::blank_source_constraints_are_deep_copied"],
  ),
  obligation(
    "rules-srl-wellformed-stratified",
    "rules",
    "srl",
    "MUST",
    "Pinned SRL syntax, well-formedness, stratification, and supported evaluation cases pass.",
    "implemented-tested-subset",
    ["lib/oxshacl/src/srl.rs", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "rules-open-execution-surfaces",
    "rules",
    "srl",
    "MUST",
    "Removed FOR/IN clauses fail during parsing; blank-node body matching and unsupported heads do not execute silently.",
    "parser-and-execution-fail-closed",
    ["lib/oxshacl/src/srl/parser.rs", "lib/oxshacl/src/srl/evaluate.rs"],
  ),
  obligation(
    "rules-graph-and-global-condition-syntax",
    "sparql",
    "rules-graph",
    "MUST",
    "RulesGraph identifiers are IRIs, and global conditions without specified focus-node semantics fail closed.",
    "implemented-tested-draft-open",
    [
      "lib/oxshacl/src/sparql_rules.rs",
      "sparql_rules::tests::rules_graph_identifiers_and_global_conditions_fail_closed",
    ],
  ),
  obligation(
    "compact-grammar-mapping",
    "compact",
    "mapping",
    "MUST",
    "Pinned grammar and RDF mapping pairs are graph-isomorphic; Jena differential is exact.",
    "implemented-tested-informative-suite",
    ["lib/oxshacl/src/compact", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "ui-renderer-conformance",
    "ui",
    "conformance",
    "MUST",
    "Renderer and UI behavior belongs to a SHACL UI implementation.",
    "not-applicable-to-store-neutral-validator",
    [],
  ),
  obligation(
    "profiling-author-conventions",
    "profiling",
    "conformance",
    "SHOULD",
    "Profile and data author publication conventions are not claimed by internal ProfileId values.",
    "not-applicable-no-w3c-profiling-claim",
    ["lib/oxshacl/src/profile.rs"],
  ),
];

export const residualClaims = [
  "Complete SHACL 1.2 Core well-formedness and import-compatibility closure are not claimed.",
  "sh:shapesGraphWellFormed is available only as an opt-in term after certifying checked compilation; complete family conformance remains unclaimed.",
  "Application-level shapes-graph discovery, retrieval, import loading, and version-IRI resolution remain outside the store-neutral compiler API.",
  "Arbitrary user-declared named-parameter and list-parameter node-expression functions are not exposed as a general extension API.",
  "SPARQL Rules repeated firing is explicitly draft-open (data-shapes issue 1069); oxshacl applies a bounded fixpoint.",
  "SRL execution remains a fail-closed subset for blank-node body matching, unsupported lowering surfaces, and draft-open repeated-firing semantics; removed FOR/IN clauses fail during parsing.",
  "The SRL RDF Rules Syntax section is placeholder text and the public SRL surface has inference but no QUERY operation.",
  "SPARQL LATERAL fails closed in oxshacl policy when dependency feature unification exposes it.",
  "SHACL UI and W3C SHACL Profiling conformance are not claimed by oxshacl.",
  "SHACL-C executable pairs are informative, not a normative W3C test suite.",
];

function obligation(id, document, section, level, summary, status, evidence) {
  return { id, document, section, level, summary, status, evidence };
}

export const candidateReviewedObligations = [
  candidateObligation(
    "core-entailment-unsupported-failure",
    "SHACL12-CORE-FAILURES",
    ["core-failures"],
    "MUST",
    "An unsupported sh:entailment regime signals failure; non-IRI values are ill-formed.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/conformance.rs", "compile::tests::fails_closed_for_requested_entailment_regimes"],
    "Complete candidate failure-taxonomy closure remains unclaimed.",
  ),
  candidateObligation(
    "core-validation-input-immutability",
    "SHACL12-CORE-FAILURES",
    ["core-failures"],
    "MUST",
    "Validation does not mutate the data graph or shapes graph.",
    "ordinary-implemented-by-api",
    ["lib/oxshacl/src/model.rs", "lib/oxshacl/src/validate.rs"],
    "Candidate execution is pending; the owned snapshot API is ordinary implementation evidence.",
  ),
  candidateObligation(
    "core-property-value-union-default",
    "SHACL12-CORE-TARGETS-PATHS",
    ["core-targets-and-value-nodes"],
    "ALGORITHM",
    "For property shapes, union path values with sh:values output and evaluate sh:defaultValue only when the combined set is empty.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/validate.rs", "lib/oxshacl/tests/core_values.rs", "commit:6c317a9a0448c9c92e6e47cf90e4434751b24a15"],
    "This explicit candidate algorithm obligation is not inferred from a BCP14 keyword census.",
  ),
  candidateObligation(
    "core-well-formed-shapes-graph",
    "SHACL12-CORE-SHAPES-GRAPH",
    ["core-shapes-graph"],
    "MUST",
    "Complete Core conformance requires all candidate syntax rules and compatible import closure.",
    "residual-not-claimed",
    ["lib/oxshacl/src/profile.rs", "compile::tests::complete_claim_remains_unavailable"],
    "The candidate has 113 syntax-rule IDs, including one corrected text. Count equality does not prove prose equivalence or complete closure.",
  ),
  candidateObligation(
    "core-report-graph",
    "SHACL12-CORE-REPORTS",
    ["core-reports"],
    "MUST",
    "Validation report graph contents are compared exactly after canonicalization.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/examples/w3c_runner/report_compare.rs"],
    "No candidate report suite has executed.",
  ),
  candidateObligation(
    "core-subclass-hierarchy-source",
    "SHACL12-CORE-TARGETS-PATHS",
    ["core-targets-and-value-nodes"],
    "SHOULD",
    "Applications can include shapes-graph rdfs:subClassOf triples in SHACL type checks.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/control.rs", "validate::semantics::tests::subclass_hierarchy_can_include_the_shapes_graph"],
    "Application-level graph discovery remains outside the store-neutral API.",
  ),
  candidateObligation(
    "core-shapes-graph-well-formed-flag",
    "SHACL12-CORE-REPORTS",
    ["core-reports"],
    "SHOULD",
    "A processor checking complete well-formedness should report sh:shapesGraphWellFormed.",
    "ordinary-implemented-tested-opt-in",
    ["lib/oxshacl/src/report.rs", "core_well_formed::well_formed_report_term_is_opt_in_and_requires_certifying_compile"],
    "The opt-in term does not imply complete candidate family conformance.",
  ),
  candidateObligation(
    "sparql-prefix-collection",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "Explicit prefix roots, inverse owl:versionIRI/import closure, datatypes, and duplicate mappings are enforced.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/prefixes.rs"],
    "Candidate SPARQL execution is pending.",
  ),
  candidateObligation(
    "sparql-resulting-query-parse",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "The resulting query is parsed during compilation and parse errors signal failure.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/sparql/policy.rs"],
    "Candidate SPARQL execution is pending.",
  ),
  candidateObligation(
    "sparql-prebinding-restrictions",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "MINUS, pre-bound VALUES variables, and AS rebinding are rejected structurally; SERVICE is disabled fail-closed.",
    "ordinary-implemented-tested",
    ["sparql::policy::tests::rejects_values_and_as_for_any_prebound_variable"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-path-substitution",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "PATH occurs only as a triple predicate and is replaced by valid surface syntax for complex SHACL paths.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/path.rs", "sparql::policy::tests::substitutes_only_legal_path_variables"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-solution-failure",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "A true ?failure solution aborts validation and does not create a result.",
    "ordinary-implemented-tested",
    ["sparql::tests::true_failure_binding_aborts_validation"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-result-mapping",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "Focus, value, path, message, severity, source constraint, and component bindings map to results.",
    "ordinary-implemented-tested",
    ["sparql::tests::explicit_result_bindings_map_in_normative_precedence_order", "sparql::tests::completed_results_apply_property_shape_and_custom_component_fallbacks", "sparql::tests::an_unbound_value_maps_only_when_the_value_node_is_unambiguous"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-message-interpolation",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "SHOULD",
    "Declared messages interpolate SELECT bindings and custom parameter bindings.",
    "ordinary-implemented-tested",
    ["sparql::tests::solution_bindings_interpolate_declared_messages"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-result-annotations",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MAY",
    "Declared result annotations use solution bindings or constant fallbacks and are emitted on validation-result nodes.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/result_annotations.rs", "lib/oxshacl/tests/result_annotations.rs"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-custom-parameter-syntax",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "Parameter NCNames, VARNAMEs, reserved names, uniqueness, boolean optionality, and a mandatory parameter are enforced.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/custom.rs"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-parameter-shape-conformance",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "Constraint values conform to constraints declared on parameter shapes.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/custom.rs", "compile::tests::custom_parameter_shapes_are_enforced"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-validator-query-roles",
    "SHACL12-SPARQL-CONSTRAINTS",
    ["sparql-constraints"],
    "MUST",
    "Every declared validator is checked: node/property validators are SELECT and generic validators are ASK.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/custom.rs", "compile::custom::tests::validator_properties_enforce_their_normative_query_roles", "compile::custom::tests::every_declared_validator_is_syntax_checked_even_when_not_selected"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "sparql-select-expression-syntax",
    "SHACL12-SPARQL-NODE-EXPRESSIONS",
    ["sparql-node-expressions"],
    "MUST",
    "SELECT expressions use one xsd:string query, project exactly one in-scope variable, and have at most one prefix root.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/compile/node_expression.rs", "node_expressions::sparql_select_expression_syntax_is_checked_before_evaluation"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "node-expression-processor",
    "SHACL12-NODEEXPR-CONFORMANCE",
    ["node-expression-conformance"],
    "MUST",
    "Candidate node-expression syntax and evaluation declarations execute against their exact source identity.",
    "candidate-unexecuted",
    ["oxigraph.shacl-candidate-inventory/v1 nodeExpressions declarations"],
    "The candidate has 143 declared cases and three reviewed syntax-text changes; no outcome is claimed before E4.",
  ),
  candidateObligation(
    "node-by-expression-source-copy",
    "SHACL12-NODEEXPR-OPERATORS",
    ["node-expression-operators"],
    "MUST",
    "Blank output shapes used as sourceConstraint are deep-copied into the report.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/report.rs", "report::tests::blank_source_constraints_are_deep_copied"],
    "Candidate interaction coverage remains unexecuted.",
  ),
  candidateObligation(
    "rules-srl-syntax-recognition",
    "SHACL12-RULES-CONCRETE-SYNTAX",
    ["sparql-rl-text-syntax"],
    "MUST",
    "Recognize the exact candidate SPARQL-RL grammar and reject syntax outside the supported grammar without relying on historical production identities.",
    "ordinary-implemented-tested-subset",
    ["lib/oxshacl/src/srl/lexer.rs", "lib/oxshacl/src/srl/parser.rs", "lib/oxshacl/tests/srl_clause_inventory.rs"],
    "The candidate grammar has 153 productions and is distinct from the historical 156-production TSV. Candidate syntax cases remain unexecuted.",
  ),
  candidateObligation(
    "rules-srl-wellformed-stratification",
    "SHACL12-RULES-WELLFORMED-STRATIFICATION",
    ["sparql-rl-wellformed-stratification"],
    "MUST",
    "Produce dependency and stratification outcomes compatible with the candidate conditions; the example construction algorithm is not mandatory.",
    "ordinary-implemented-tested-subset",
    ["lib/oxshacl/src/srl/check.rs", "lib/oxdatalog/src", "srl::check::tests::closed_recursive_dependency_is_rejected"],
    "Closed recursive dependency rejection is a conservative local policy for an undefined outcome, not a claimed candidate MUST.",
  ),
  candidateObligation(
    "rules-srl-evaluation",
    "SHACL12-RULES-EVALUATION",
    ["sparql-rl-evaluation", "sparql-rl-expression-evaluation", "sparql-rl-ground-data", "sparql-rl-imports"],
    "ALGORITHM",
    "Evaluate prepared strata, run-once and general rules, expressions, imports, and ground DATA with cumulative resource controls.",
    "ordinary-tested-subset-complete-ground-data-and-srl-bnode-evidence-bound",
    [
      "lib/oxshacl/src/srl/evaluate.rs",
      "lib/oxshacl/src/srl/evaluate/native.rs",
      "lib/oxshacl/src/srl/imports.rs",
      "lib/oxshacl/tests/srl_data_terms.rs",
      "lib/oxshacl/tests/srl_bnode.rs",
      "commit:2e63c6920a9c51e7b078d9a87c3070f6a8fb3978",
      "programme-task-evidence/workflow-e12bca4c-4d2c-48b3-8f13-d9fcfcf5c4c7",
      "target/engineering-delivery/adr0046-srl-data/accepted-EGzKud.json#39955651bc5bf1ecf071fff9c3fbf1df1dced2432861b3c3102ddbdbb989807f",
      "commit:f706742b17e6674360c34cf6bdfc3b1b59ab59f3",
      "programme-task-evidence/workflow-384d7494-7e95-49a0-8f71-442839b63a2c",
      "target/engineering-delivery/adr0046-srl-bnode/accepted-8tVvxP.json#962baef59d23bc12cfa28421a437daa4d7ffa6fd1077cee5b08b72064b06ae9c",
    ],
    "Complete-ground-DATA and SRL BNODE slices are bound to their exact accepted commits and workflow evidence. Candidate execution remains unobserved.",
  ),
  candidateObligation(
    "rules-srl-data-source-interpretation",
    "SHACL12-RULES-EVALUATION",
    ["sparql-rl-evaluation", "sparql-rl-ground-data"],
    "AMBIGUOUS-SOURCE",
    "Use the accepted local base-plus-inline DATA interpretation while recording that the pinned eval-rule-set pseudocode passes literal G0 to evalRule DATA matching.",
    "ordinary-local-contract-tested-source-ambiguous",
    ["docs/adr/0046-shacl-12-editors-draft-realignment.md", "commit:e9a285c8217087a255072271f1bb444e70d43d32", "lib/oxshacl/tests/srl_data_semantics.rs"],
    "Accepted local base-plus-inline DATA interpretation; differs from literal G0 call sites; upstream intent unresolved. Neither candidate pass results nor the separate component-notation flag inversion closes this discrepancy.",
    "source-reviewed-with-explicit-ambiguity",
  ),
  candidateObligation(
    "rules-deleted-for-clause-rejection",
    "SHACL12-RULES-CONCRETE-SYNTAX",
    ["sparql-rl-text-syntax"],
    "MUST",
    "The deleted FOR rule clause is rejected as syntax.",
    "ordinary-parser-fail-closed",
    ["lib/oxshacl/src/srl/parser.rs", "lib/oxshacl/tests/srl_clause_inventory.rs"],
    "IN is not a deleted rule clause: IN and NOT IN remain membership expressions in candidate grammar production 107.",
  ),
  candidateObligation(
    "rules-body-abbreviations",
    "SHACL12-RULES-EVALUATION",
    ["sparql-rl-evaluation"],
    "ALGORITHM",
    "Collections, property lists, reifiers, annotations, and body blank-node labels participate in matching and dependency analysis with their specified assertion behavior.",
    "ordinary-implemented-tested-subset",
    ["lib/oxshacl/src/srl/parser/nodes.rs", "lib/oxshacl/src/srl/evaluate.rs", "lib/oxshacl/tests/srl_body_abbreviations.rs", "commit:6e933eea37bd0f27660ee4a3471cdf11b910c949"],
    "Do not retain the historical blanket body-abbreviation refusal. Candidate cases remain unexecuted.",
  ),
  candidateObligation(
    "rules-rdf-syntax-boundaries",
    "SHACL12-RULES-CONCRETE-SYNTAX",
    ["rdf-shacl-rule-syntax"],
    "MUST",
    "RDF sh:SPARQLRule support is distinct from RDF sh:TripleRule and sh:SPARQLRuleTemplate compilation and from textual SPARQL-RL syntax.",
    "explicit-unsupported-subset",
    ["lib/oxshacl/src/sparql_rules.rs", "oxigraph.shacl-candidate-inventory/v1 unsupported inference declarations"],
    "The programmatic Rust Datalog rule API is not an RDF sh:TripleRule or sh:SPARQLRuleTemplate compiler. The two sh:SPARQLRuleTemplate fixtures and two sh:TripleRule fixtures remain predeclared unsupported.",
  ),
  candidateObligation(
    "rules-graph-identifier-syntax",
    "SHACL12-SPARQL-RULES",
    ["inference-rules-graph"],
    "MAY-AND-SYNTAX",
    "Rules graphs have graph-role semantics and sh:RulesGraph is used only with an IRI graph identifier.",
    "ordinary-implemented-tested-subset",
    ["lib/oxshacl/src/sparql_rules.rs", "sparql_rules::tests::rules_graph_identifiers_and_global_conditions_fail_closed"],
    "Candidate rule-graph cases remain unexecuted.",
  ),
  candidateObligation(
    "rules-global-condition-policy",
    "SHACL12-SPARQL-RULES",
    ["inference-global-rules", "inference-rule-conditions"],
    "LOCAL-POLICY",
    "Global rules execute with an empty focus set; conditions are defined for shape-rule target nodes, so the implementation rejects a global rule carrying a condition.",
    "ordinary-local-policy-tested",
    ["lib/oxshacl/src/sparql_rules.rs", "sparql_rules::tests::rules_graph_identifiers_and_global_conditions_fail_closed"],
    "The candidate does not explicitly impose a MUST-reject global-condition rule. Keep the local fail-closed policy distinct from candidate normative wording.",
  ),
  candidateObligation(
    "rules-expected-predicate-lifecycle",
    "SHACL12-SPARQL-RULES",
    ["inference-expected-predicate", "inference-rule-layers", "inference-rules-graph"],
    "ALGORITHM",
    "Prepare expected derived values once from the layer-start snapshot, expose them during that layer, then remove derived-only triples and reifiers while retaining base and independently inferred overlap.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/sparql_rules.rs", "lib/oxshacl/src/sparql_rules/execution.rs", "lib/oxshacl/src/sparql_rules/derived.rs", "lib/oxshacl/tests/sparql_expected_predicate.rs", "commit:85580fc93f122565bdc0de48aef42a334174bb9e"],
    "This closes the bounded local expectedPredicate lifecycle only. It does not implement RDF sh:runOnce, sh:tempTriple, sh:TripleRule, templates, custom processors, or optional sh:sourceRule output.",
  ),
  candidateObligation(
    "rules-run-once-and-temporary-triples",
    "SHACL12-SPARQL-RULES",
    ["inference-run-once", "inference-temporary-triples"],
    "ALGORITHM",
    "RDF sh:runOnce and temporary-triple lifecycle are explicit candidate execution semantics.",
    "unsupported",
    ["oxigraph.shacl-candidate-inventory/v1 unsupported inference declarations"],
    "RDF sh:runOnce and sh:tempTriple execution remain predeclared unsupported. They are not dismissed as optional sourceRule provenance and are distinct from SPARQL-RL run-once strata.",
  ),
  candidateObligation(
    "rules-rule-processor-failure",
    "SHACL12-SPARQL-RULES",
    ["inference-custom-processors"],
    "MUST",
    "A rule or rule set requesting an unsupported sh:ruleProcessor reports failure.",
    "ordinary-implemented-tested",
    ["lib/oxshacl/src/sparql_rules.rs", "commit:e9a285c8217087a255072271f1bb444e70d43d32"],
    "No custom processor identity or non-default processor execution is advertised.",
  ),
  candidateObligation(
    "rules-abstract-query-surface",
    "SHACL12-RULES-CONFORMANCE",
    ["sparql-rl-conformance"],
    "ABSTRACT-OPERATION",
    "Infer produces inferred triples; Query is Infer followed by goal matching over the resulting graph.",
    "ordinary-implemented-subset",
    ["lib/oxshacl/src/srl.rs", "lib/oxshacl/tests/srl_query.rs"],
    "The candidate supplies no concrete Query grammar. The local single-triple goal restriction is not reported as a specification MUST.",
  ),
  candidateObligation(
    "compact-grammar-mapping",
    "SHACL12-CS-PARSER",
    ["compact-parser"],
    "MUST",
    "Candidate grammar and RDF mapping pairs are compared graph-isomorphically under their exact source identities.",
    "candidate-unexecuted-ordinary-local-oracles-exist",
    ["lib/oxshacl/src/compact", "lib/oxshacl/tests/compact_syntax_inventory.rs", "lib/oxshacl/tests/compact_roundtrip.rs", "oxigraph.shacl-candidate-inventory/v1 compactSyntax declarations"],
    "The candidate 32-pair lane remains unexecuted and informative, with no conformance promotion.",
  ),
  candidateObligation(
    "ui-renderer-conformance",
    "SHACL12-UI-ROLE",
    ["ui-role"],
    "MUST",
    "Renderer and UI behavior belongs to a SHACL UI implementation.",
    "not-applicable-to-store-neutral-validator",
    [],
    "Candidate source review does not change the product role.",
  ),
  candidateObligation(
    "profiling-author-conventions",
    "SHACL12-PROFILING-DESCRIPTION",
    ["profiling-description"],
    "SHOULD",
    "Profile and data-author publication conventions are not claimed by internal ProfileId values.",
    "not-applicable-no-w3c-profiling-claim",
    ["lib/oxshacl/src/profile.rs"],
    "Dated profile identities and historical receipts remain unchanged.",
  ),
  candidateObligation(
    "profiling-conformance-provenance-rules",
    "SHACL12-PROFILING-NEGOTIATION",
    ["profiling-conforms-to-shapes-graph", "profiling-conforms-to-specification"],
    "RULE",
    "Keep validation-activity graph conformance distinct from profile-to-specification conformance propagation.",
    "not-applicable-no-w3c-profiling-claim",
    ["lib/oxshacl/src/profile.rs", "lib/oxshacl/src/profile/negotiation.rs"],
    "The deleted rule-conformsto anchor does not transfer to either successor by name. Oxigraph does not claim these publisher/data-author inference roles.",
  ),
];

export const candidateResidualClaims = [
  "All candidate collections are bound to data-shapes commit 0ccfab4f28324edaac59a1227f8c60ad5b7bbf89 and remain candidate-unexecuted until E4 ordinary execution.",
  "Historical mappings, dated profiles, source IRIs, the 156-production SRL TSV, fixed-path artifacts, receipts, and archive validators retain their historical commit and hashes.",
  "Complete SHACL 1.2 Core well-formedness, import compatibility, SPARQL Extensions, Node Expressions, Inference Rules, SPARQL-RL, Compact Syntax, UI, and Profiling conformance are not claimed.",
  "The candidate SPARQL Extensions inventory has 46 syntax-rule IDs; ten rule IDs moved to the distinct 25-ID Inference Rules source. Historical 56-ID evidence remains historical.",
  "The candidate SPARQL-RL grammar has 153 productions and is a distinct identity from the historical 156-production inventory and receipts.",
  "RDF sh:runOnce, sh:tempTriple, sh:TripleRule, and sh:SPARQLRuleTemplate execution remain exact predeclared unsupported surfaces; the programmatic Datalog API is not an RDF compiler.",
  "sh:expectedPredicate has bounded ordinary implementation evidence for layer-start derivation and cleanup, but supporting it does not close the inference-rules family or optional sh:sourceRule provenance.",
  "Accepted local base-plus-inline DATA interpretation; differs from literal G0 call sites; upstream intent unresolved. This prevents an unqualified literal candidate-algorithm equivalence claim and does not authorize changing accepted DATA semantics.",
  "Complete-ground-DATA slice D and SRL BNODE slice N are bound to exact accepted commits, acceptance artifacts, review hashes, workflow runs, and programme evidence keys before E3 adoption.",
  "The candidate public abstract Query operation exists, but no concrete Query grammar is supplied and the local single-triple goal restriction is not a specification MUST.",
  "Candidate Node Expressions retain 35 syntax-rule IDs but include reviewed semantic text changes for InstancesOfExpression, NodesMatchingExpression, and CustomListParameterFunction.",
  "The profiling rule-conformsto anchor is deleted and replaced by semantically distinct conforms-to-shapes-graph and conforms-to-specification rules; neither transfers historical evidence or creates a W3C profiling role for Oxigraph.",
  "SHACL UI and W3C Profiling roles remain outside the store-neutral validator, and SHACL-C upstream pairs remain informative.",
  "A candidate suite pass records only exact observed cases and cannot resolve source ambiguity, close untested prose, change preexecution declarations, qualify, promote, or replace historical evidence.",
];

function candidateObligation(
  id,
  mappingId,
  sourceFacetIds,
  level,
  summary,
  implementationStatus,
  evidence,
  residual,
  sourceStatus = "source-reviewed",
) {
  return {
    id,
    mappingId,
    sourceFacetIds,
    level,
    summary,
    sourceStatus,
    implementationStatus,
    candidateExecutionStatus: "unexecuted",
    evidence,
    residual,
  };
}
