export const reviewedObligations = [
  obligation(
    "core-entailment-unsupported-failure",
    "core",
    "shacl-rdfs",
    "MUST",
    "An unsupported sh:entailment regime signals failure; non-IRI values are ill-formed.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/conformance.rs", "compile::tests::fails_closed_for_requested_entailment_regimes"],
  ),
  obligation(
    "core-validation-input-immutability",
    "core",
    "validation-definition",
    "MUST",
    "Validation does not mutate the data graph or shapes graph.",
    "implemented-by-api",
    ["lib/oxshacl/src/model.rs", "lib/oxshacl/src/validate.rs"],
  ),
  obligation(
    "core-well-formed-shapes-graph",
    "core",
    "shapes-graph-well-formed",
    "MUST",
    "Complete Core conformance requires all syntax rules and compatible import closure.",
    "residual-not-claimed",
    ["lib/oxshacl/src/profile.rs", "compile::tests::complete_claim_remains_unavailable"],
  ),
  obligation(
    "core-report-graph",
    "core",
    "validation-report",
    "MUST",
    "Validation report graph contents are compared exactly after canonicalization.",
    "implemented-tested",
    ["lib/oxshacl/examples/w3c_runner/report_compare.rs", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "core-subclass-hierarchy-source",
    "core",
    "subClassOfInShapesGraph",
    "SHOULD",
    "Applications can include shapes-graph rdfs:subClassOf triples in SHACL type checks.",
    "implemented-tested",
    ["lib/oxshacl/src/control.rs", "validate::semantics::tests::subclass_hierarchy_can_include_the_shapes_graph"],
  ),
  obligation(
    "core-shapes-graph-well-formed-flag",
    "core",
    "validation-report",
    "SHOULD",
    "A processor checking complete well-formedness should report sh:shapesGraphWellFormed.",
    "implemented-tested-opt-in",
    [
      "lib/oxshacl/src/report.rs",
      "core_well_formed::well_formed_report_term_is_opt_in_and_requires_certifying_compile",
    ],
  ),
  obligation(
    "sparql-prefix-collection",
    "sparql",
    "sparql-prefixes",
    "MUST",
    "Explicit prefix roots, inverse owl:versionIRI/import closure, datatypes, and duplicate mappings are enforced.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/prefixes.rs"],
  ),
  obligation(
    "sparql-resulting-query-parse",
    "sparql",
    "sparql-prefixes",
    "MUST",
    "The resulting query is parsed during compilation and parse errors signal failure.",
    "implemented-tested",
    ["lib/oxshacl/src/sparql/policy.rs"],
  ),
  obligation(
    "sparql-prebinding-restrictions",
    "sparql",
    "pre-binding",
    "MUST",
    "MINUS, pre-bound VALUES variables, and AS rebinding are rejected structurally; SERVICE is disabled fail-closed.",
    "implemented-tested",
    ["sparql::policy::tests::rejects_values_and_as_for_any_prebound_variable"],
  ),
  obligation(
    "sparql-path-substitution",
    "sparql",
    "PATH-position",
    "MUST",
    "PATH occurs only as a triple predicate and is replaced by valid surface syntax for complex SHACL paths.",
    "implemented-tested",
    ["lib/oxshacl/src/path.rs", "sparql::policy::tests::substitutes_only_legal_path_variables"],
  ),
  obligation(
    "sparql-solution-failure",
    "sparql",
    "sparql-constraints-validation-rule",
    "MUST",
    "A true ?failure solution aborts validation and does not create a result.",
    "implemented-tested",
    ["sparql::tests::true_failure_binding_aborts_validation"],
  ),
  obligation(
    "sparql-result-mapping",
    "sparql",
    "sparql-constraints-variables",
    "MUST",
    "Focus, value, path, message, severity, source constraint, and component bindings map to results.",
    "implemented-tested",
    [
      "sparql::tests::explicit_result_bindings_map_in_normative_precedence_order",
      "sparql::tests::completed_results_apply_property_shape_and_custom_component_fallbacks",
      "sparql::tests::an_unbound_value_maps_only_when_the_value_node_is_unambiguous",
    ],
  ),
  obligation(
    "sparql-message-interpolation",
    "sparql",
    "sparql-constraints-variables",
    "SHOULD",
    "Declared messages interpolate SELECT bindings and custom parameter bindings.",
    "implemented-tested",
    ["sparql::tests::solution_bindings_interpolate_declared_messages"],
  ),
  obligation(
    "sparql-result-annotations",
    "sparql",
    "sparql-constraints-annotations",
    "MAY",
    "Declared result annotations use solution bindings or constant fallbacks and are emitted on validation-result nodes.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/result_annotations.rs", "lib/oxshacl/tests/result_annotations.rs"],
  ),
  obligation(
    "sparql-custom-parameter-syntax",
    "sparql",
    "constraint-components-parameters",
    "MUST",
    "Parameter NCNames, VARNAMEs, reserved names, uniqueness, boolean optionality, and a mandatory parameter are enforced.",
    "implemented-tested",
    [
      "compile::custom::tests::extracts_the_longest_eligible_ncname_suffix",
      "compile::custom::tests::constraint_components_and_parameter_paths_have_required_node_kinds_and_counts",
      "compile::custom::tests::parameter_names_must_be_varnames_unique_and_not_reserved",
      "compile::custom::tests::optional_parameters_require_one_valid_boolean_and_one_mandatory_peer",
    ],
  ),
  obligation(
    "sparql-parameter-shape-conformance",
    "sparql",
    "constraint-components-parameters",
    "MUST",
    "Constraint values conform to constraints declared on parameter shapes.",
    "implemented-tested",
    ["lib/oxshacl/src/compile/custom.rs", "compile::tests::custom_parameter_shapes_are_enforced"],
  ),
  obligation(
    "sparql-validator-query-roles",
    "sparql",
    "constraint-components-validators",
    "MUST",
    "Every declared validator is checked: node/property validators are SELECT and generic validators are ASK.",
    "implemented-tested",
    [
      "lib/oxshacl/src/compile/custom.rs",
      "compile::custom::tests::validator_properties_enforce_their_normative_query_roles",
      "compile::custom::tests::every_declared_validator_is_syntax_checked_even_when_not_selected",
    ],
  ),
  obligation(
    "sparql-select-expression-syntax",
    "sparql",
    "SelectExpression",
    "MUST",
    "SELECT expressions use one xsd:string query, project exactly one in-scope variable, and have at most one prefix root.",
    "implemented-tested",
    [
      "lib/oxshacl/src/compile/node_expression.rs",
      "node_expressions::sparql_select_expression_syntax_is_checked_before_evaluation",
    ],
  ),
  obligation(
    "node-expression-processor",
    "nodeExpressions",
    "conformance",
    "MUST",
    "Pinned node-expression syntax and evaluation fixtures pass exactly.",
    "implemented-tested",
    ["target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "node-by-expression-source-copy",
    "nodeExpressions",
    "nodeByExpression",
    "MUST",
    "Blank output shapes used as sourceConstraint are deep-copied into the report.",
    "implemented-tested",
    ["lib/oxshacl/src/report.rs", "report::tests::blank_source_constraints_are_deep_copied"],
  ),
  obligation(
    "rules-srl-wellformed-stratified",
    "rules",
    "srl",
    "MUST",
    "Pinned SRL syntax, well-formedness, stratification, and supported evaluation cases pass.",
    "implemented-tested-subset",
    ["lib/oxshacl/src/srl.rs", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "rules-open-execution-surfaces",
    "rules",
    "srl",
    "MUST",
    "FOR/IN shape integration, blank-node body matching, and unsupported heads do not execute silently.",
    "unsupported-fail-closed",
    ["lib/oxshacl/src/srl/evaluate.rs"],
  ),
  obligation(
    "rules-graph-and-global-condition-syntax",
    "sparql",
    "rules-graph",
    "MUST",
    "RulesGraph identifiers are IRIs, and global conditions without specified focus-node semantics fail closed.",
    "implemented-tested-draft-open",
    [
      "lib/oxshacl/src/sparql_rules.rs",
      "sparql_rules::tests::rules_graph_identifiers_and_global_conditions_fail_closed",
    ],
  ),
  obligation(
    "compact-grammar-mapping",
    "compact",
    "mapping",
    "MUST",
    "Pinned grammar and RDF mapping pairs are graph-isomorphic; Jena differential is exact.",
    "implemented-tested-informative-suite",
    ["lib/oxshacl/src/compact", "target/w3c/shacl-1.2/run-receipt.json"],
  ),
  obligation(
    "ui-renderer-conformance",
    "ui",
    "conformance",
    "MUST",
    "Renderer and UI behavior belongs to a SHACL UI implementation.",
    "not-applicable-to-store-neutral-validator",
    [],
  ),
  obligation(
    "profiling-author-conventions",
    "profiling",
    "conformance",
    "SHOULD",
    "Profile and data author publication conventions are not claimed by internal ProfileId values.",
    "not-applicable-no-w3c-profiling-claim",
    ["lib/oxshacl/src/profile.rs"],
  ),
];

export const residualClaims = [
  "Complete SHACL 1.2 Core well-formedness and import-compatibility closure are not claimed.",
  "sh:shapesGraphWellFormed is available only as an opt-in term after certifying checked compilation; complete family conformance remains unclaimed.",
  "Application-level shapes-graph discovery, retrieval, import loading, and version-IRI resolution remain outside the store-neutral compiler API.",
  "Arbitrary user-declared named-parameter and list-parameter node-expression functions are not exposed as a general extension API.",
  "SPARQL Rules repeated firing is explicitly draft-open (data-shapes issue 1069); oxshacl applies a bounded fixpoint.",
  "SRL execution remains a fail-closed subset for FOR/IN shape integration (data-shapes issue 1074), blank-node body matching, unsupported lowering surfaces, and draft-open semantics.",
  "The SRL RDF Rules Syntax section is placeholder text and the public SRL surface has inference but no QUERY operation.",
  "SPARQL LATERAL fails closed in oxshacl policy when dependency feature unification exposes it.",
  "SHACL UI and W3C SHACL Profiling conformance are not claimed by oxshacl.",
  "SHACL-C executable pairs are informative, not a normative W3C test suite.",
];

function obligation(id, document, section, level, summary, status, evidence) {
  return { id, document, section, level, summary, status, evidence };
}
